name: ic_ses_yalnizlik_gunlugu
description: İç Ses Günlüğü - konuş, yaz, rahatla
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # UI & icons
  cupertino_icons: ^1.0.8

  # Konuşma -> Yazı
  speech_to_text: ^6.6.0

  # Yazı -> Konuşma
  flutter_tts: ^3.8.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
